CREATE TABLE snippets (

     id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
     title VARCHAR(100) not null ,
     content text not null ,
     created timestamptz NOT NULL,
     updated timestamptz not null DEFAULT now(),
     expires timestamptz not null 
);

CREATE INDEX idx_snippets_created ON snippets (created);
