CREATE TABLE snippets (

     id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
     title VARCHAR(100) not null ,
     environment text not null ,
     content text not null ,
     created timestamp NOT NULL,
     updated timestamp not null DEFAULT now(),
     expires timestamp not null 
);

CREATE INDEX idx_snippets_created ON snippets (created);
